CREATE TABLE IF NOT EXISTS genres (
	id SERIAL PRIMARY KEY NOT NULL,
	genre VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS production_companies (
	id SERIAL PRIMARY KEY NOT NULL,
	prod_comp VARCHAR
);

CREATE TABLE IF NOT EXISTS languages (
	id SERIAL PRIMARY KEY NOT NULL,
	lang VARCHAR
);

CREATE TABLE IF NOT EXISTS movies (
	id SERIAL PRIMARY KEY NOT NULL,
	budget INT NOT NULL,
    imdb_id VARCHAR NOT NULL,
    revenue INT NOT NULL,
    release_date DATE NOT NULL,
    title VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS movie_genre_nm (
	movie_id INT NOT NULL REFERENCES movies,
	genre_id INT NOT NULL REFERENCES genres
);

CREATE TABLE IF NOT EXISTS movie_language_nm (
	movie_id INT NOT NULL REFERENCES movies,
	language_id INT NOT NULL REFERENCES languages
);
