CREATE TABLE IF NOT EXISTS genres (
	id SERIAL PRIMARY KEY NOT NULL,
	genre VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS production_companies (
	id SERIAL PRIMARY KEY NOT NULL,
	prod_comp VARCHAR
);

CREATE TABLE IF NOT EXISTS languages (
	id SERIAL PRIMARY KEY NOT NULL,
	lang VARCHAR
);

